# <font color="blue"> MBA em Ciência de Dados</font>
# <font color="blue">Programação para Ciência de Dados</font>

## <font color="blue">Numpy Parte II e Matplotlib - Avaliação</font>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo utiliza corretamente broadcasting para somar o vetor `v` em cada **linha** da matriz `A`, sendo que `v` e `A` são definidos como:
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a) A[:]+v[:]<br>
b) A + v<br>
c) A = A + v.reshape(1,-1)<br>
**d) Todas as alternativas estão corretas**

In [9]:
A = np.zeros((4,4))
v = np.arange(4)
print(A)
print(v)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3]


In [3]:
A[:]+v[:]

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [5]:
A+v

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [10]:
X = A + v.reshape(1,-1)
X

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

### Exercício 2)
Qual das alternativas explica corretamente como o array `W` está sendo calculado no código abaixo?
```python
u = np.random.randint(0,30,7).reshape(1,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v * u
```

a) `W` é um array unidimensional com 10 elementos, resultado da multiplicação dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) `W` é um array unidimensional com 7 elementos, resultado da multiplicação dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.<br>
c) `W` é um array bidimensional com 7 linhas e 10 colunas, resultado da multiplicação do array `v` com broadcasting em 7 linhas e o array `u` com broadcasting em 10 linhas.<br>
**d) `W` é um array bidimensional com 10 linhas e 7 colunas, resultado da multiplicação do array `v` com broadcasting em 7 colunas e do array `u` com broadcasting em 10 linhas.<br>**

In [12]:
u = np.random.randint(0,30,7).reshape(1,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v * u
print(W)

[[ 38  58   8  22  40  32  20]
 [418 638  88 242 440 352 220]
 [171 261  36  99 180 144  90]
 [ 57  87  12  33  60  48  30]
 [342 522  72 198 360 288 180]
 [152 232  32  88 160 128  80]
 [ 57  87  12  33  60  48  30]
 [266 406  56 154 280 224 140]
 [228 348  48 132 240 192 120]
 [ 38  58   8  22  40  32  20]]


In [13]:
print(u)
print(v)

[[19 29  4 11 20 16 10]]
[[ 2]
 [22]
 [ 9]
 [ 3]
 [18]
 [ 8]
 [ 3]
 [14]
 [12]
 [ 2]]


### Exercício 3)
Considere a matriz abaixo. Utilizando redução por soma, encontre o **índice da linha** que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha 6<br>
b) linha 0<br>
**c) linha 8<br>**
d) linha 9

In [14]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])


In [25]:
print('Posição do maior valor dentre todos na matriz: ', np.argmax(np.sum(A, axis=1))) # lineariza a matriz com A.ravel() e 
                                                                      # retorna a posicão do maior valor

Posição do maior valor dentre todos na matriz:  8


In [30]:
print('Soma dos valores das linhas: ', np.sum(A,axis=1)) # soma os valores das linhas

Soma dos valores das linhas:  [53 47 25 29 37 44 46 45 60 35]


In [18]:
sum([8, 8, 1, 8, 4, 1, 8, 9, 7, 6])

60

In [19]:
A[8]

array([8, 8, 1, 8, 4, 1, 8, 9, 7, 6])

### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o valor da **maior média** calculada sobre os valores das colunas?

a) 5.8<br>
**b) 6.5<br>**
c) 3.5<br>
d) 9.1

In [33]:
# Solucao
print('Média dos valores das linhas: ', np.max( np.average(A, axis=0)))

Média dos valores das linhas:  6.5


### Exercício 5)
Suponha que a variável `A` no código abaixo é um array bidimensional com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
**b) Substituindo o maior valor de cada linha por -1<br>**
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [37]:
A = np.random.randint(0,30,size=(5,7))

Aargs = np.argsort(A)
print(A)
# print(Aargs)

A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
# print(A)

[[ 5  3 26  3  6  0 23]
 [14  7  4 18  1 14 14]
 [24  7 16 27  6 17 24]
 [ 4 23 25 25  4 13  5]
 [27  2 23  6  5 12 22]]


In [50]:
A = np.random.randint(0,30,size=(5,7))
print(A)

[[ 1 27  0 16 20  1 11]
 [ 5 15  1 24 26 12 21]
 [14 28 13 22 14  0 13]
 [11 14 20 19 25  9  4]
 [12  3  3 19 16  8 29]]


In [51]:
Aargs = np.argsort(A)
print(Aargs)

[[2 0 5 6 3 4 1]
 [2 0 5 1 6 3 4]
 [5 2 6 0 4 3 1]
 [6 5 0 1 3 2 4]
 [1 2 5 0 4 3 6]]


In [52]:
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1


In [53]:
print(A)


[[ 1 -1  0 16 20  1 11]
 [ 5 15  1 24 -1 12 21]
 [14 -1 13 22 14  0 13]
 [11 14 20 19 -1  9  4]
 [12  3  3 19 16  8 -1]]


In [49]:
np.arange(A.shape[0])

array([0, 1, 2, 3, 4])